# Generated by Django 5.0.6 on 2024-07-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksform',
            old_name='print',
            new_name='price',
        ),
    ]
